# theme: jekyll-theme-hacker
title: Oscar de Felice homepage
logo: https://user-images.githubusercontent.com/49638680/98257151-9f5e5800-1f7f-11eb-9f42-479a4fc6cf24.png
description: My personal webspace to collect projects and ideas.